# Generated by Django 6.0.6 on 2026-06-22 13:09

import blog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, height_field='cover_height', null=True, upload_to='covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), blog.validators.validate_image_size], width_field='cover_width'),
        ),
    ]
